name: knarly_app
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: any #^2.2.2
  firebase_analytics: ^9.3.8
  firebase_auth: any #^3.0.1
  firebase_core: any
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  go_router: ^3.0.0
  http: ^1.0.0
  knarly_common:
    path: ../common
  provider: ^6.0.0

  url_launcher: ^6.0.9
  vote: any
  vote_widgets: any

dev_dependencies:
  build_runner: ^2.0.0
  go_router_builder: ^1.0.0

dependency_overrides:
  vote:
    path: ../../vote.dart/vote
  vote_widgets:
    path: ../../vote.dart/vote_widgets

flutter:
  uses-material-design: true
