name: knarly_app
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.2.2
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  go_router: ^2.2.1
  http: ^0.13.0
  knarly_common:
    path: ../common
  provider: ^6.0.0

  url_launcher: ^6.0.9
  vote: any
  vote_widgets: any

dependency_overrides:
  vote:
    path: ../../vote.dart/vote
  vote_widgets:
    path: ../../vote.dart/vote_widgets

flutter:
  uses-material-design: true
