name: knarly_server

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  functions_framework: ^0.4.1
  googleapis: ^6.0.0
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  jose: ^0.3.0
  json_annotation: ^4.3.0
  knarly_common:
    path: ../common
  shelf: ^1.2.0
  shelf_jwt_auth:
    path: ../shelf_jwt_auth
  shelf_router: ^1.0.0
  stack_trace: ^1.10.0
  vote: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.4
  functions_framework_builder: ^0.4.2
  json_serializable: ^6.0.0
  shelf_router_generator: ^1.0.0
  test: ^1.17.10
