name: knarly_common

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.4
  build_verify: ^2.0.0
  json_serializable: ^5.0.0
  pedantic: ^1.11.1
  test: ^1.17.8
