# Created with package:mono_repo v6.5.7
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.5.7
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; PKGS: common, server, shelf_jwt_auth; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:common-server-shelf_jwt_auth;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:common-server-shelf_jwt_auth
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: common_pub_upgrade
        name: common; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: common
      - name: "common; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.common_pub_upgrade.conclusion == 'success'"
        working-directory: common
      - name: "common; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.common_pub_upgrade.conclusion == 'success'"
        working-directory: common
      - id: server_pub_upgrade
        name: server; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: server
      - name: "server; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
      - name: "server; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
      - id: shelf_jwt_auth_pub_upgrade
        name: shelf_jwt_auth; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_jwt_auth
      - name: "shelf_jwt_auth; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.shelf_jwt_auth_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_jwt_auth
      - name: "shelf_jwt_auth; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.shelf_jwt_auth_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_jwt_auth
  job_003:
    name: "ensure_build; PKG: common; `dart test --run-skipped -t presubmit-only test/ensure_build_test.dart`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:common;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:common
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: common_pub_upgrade
        name: common; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: common
      - name: "common; dart test --run-skipped -t presubmit-only test/ensure_build_test.dart"
        run: dart test --run-skipped -t presubmit-only test/ensure_build_test.dart
        if: "always() && steps.common_pub_upgrade.conclusion == 'success'"
        working-directory: common
    needs:
      - job_001
      - job_002
