# Created with package:mono_repo v6.0.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.4.0
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.0.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; Flutter beta; PKG: app; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:app;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:app
            os:ubuntu-latest;pub-cache-hosted;sdk:beta
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: beta
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: app_pub_upgrade
        name: app; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: app
        run: dart pub upgrade
      - name: "app; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.app_pub_upgrade.conclusion == 'success'"
        working-directory: app
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "app; dart analyze --fatal-infos ."
        if: "always() && steps.app_pub_upgrade.conclusion == 'success'"
        working-directory: app
        run: dart analyze --fatal-infos .
  job_003:
    name: "analyze_and_format; Dart dev; PKGS: common, server, shelf_jwt_auth; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:common-server-shelf_jwt_auth;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:common-server-shelf_jwt_auth
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: common_pub_upgrade
        name: common; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: common
        run: dart pub upgrade
      - name: "common; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.common_pub_upgrade.conclusion == 'success'"
        working-directory: common
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "common; dart analyze --fatal-infos ."
        if: "always() && steps.common_pub_upgrade.conclusion == 'success'"
        working-directory: common
        run: dart analyze --fatal-infos .
      - id: server_pub_upgrade
        name: server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: server
        run: dart pub upgrade
      - name: "server; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "server; dart analyze --fatal-infos ."
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
        run: dart analyze --fatal-infos .
      - id: shelf_jwt_auth_pub_upgrade
        name: shelf_jwt_auth; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_jwt_auth
        run: dart pub upgrade
      - name: "shelf_jwt_auth; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.shelf_jwt_auth_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_jwt_auth
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "shelf_jwt_auth; dart analyze --fatal-infos ."
        if: "always() && steps.shelf_jwt_auth_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_jwt_auth
        run: dart analyze --fatal-infos .
  job_004:
    name: "ensure_build; Dart dev; PKG: common; `dart test --run-skipped -t presubmit-only test/ensure_build_test.dart`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:common;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:common
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: common_pub_upgrade
        name: common; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: common
        run: dart pub upgrade
      - name: "common; dart test --run-skipped -t presubmit-only test/ensure_build_test.dart"
        if: "always() && steps.common_pub_upgrade.conclusion == 'success'"
        working-directory: common
        run: dart test --run-skipped -t presubmit-only test/ensure_build_test.dart
    needs:
      - job_001
      - job_002
      - job_003
