# Created with package:mono_repo v5.0.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.4
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 5.0.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; PKGS: client, server, shelf_jwt_auth; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:client-server-shelf_jwt_auth;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:client-server-shelf_jwt_auth
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: client_pub_upgrade
        name: client; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: client
        run: dart pub upgrade
      - name: "client; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.client_pub_upgrade.conclusion == 'success'"
        working-directory: client
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "client; dart analyze --fatal-infos ."
        if: "always() && steps.client_pub_upgrade.conclusion == 'success'"
        working-directory: client
        run: dart analyze --fatal-infos .
      - id: server_pub_upgrade
        name: server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: server
        run: dart pub upgrade
      - name: "server; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "server; dart analyze --fatal-infos ."
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
        run: dart analyze --fatal-infos .
      - id: shelf_jwt_auth_pub_upgrade
        name: shelf_jwt_auth; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_jwt_auth
        run: dart pub upgrade
      - name: "shelf_jwt_auth; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.shelf_jwt_auth_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_jwt_auth
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "shelf_jwt_auth; dart analyze --fatal-infos ."
        if: "always() && steps.shelf_jwt_auth_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_jwt_auth
        run: dart analyze --fatal-infos .
  job_003:
    name: "ensure_build; PKG: client; `dart test --run-skipped -t presubmit-only test/ensure_build_test.dart`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:client;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:client
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: client_pub_upgrade
        name: client; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: client
        run: dart pub upgrade
      - name: "client; dart test --run-skipped -t presubmit-only test/ensure_build_test.dart"
        if: "always() && steps.client_pub_upgrade.conclusion == 'success'"
        working-directory: client
        run: dart test --run-skipped -t presubmit-only test/ensure_build_test.dart
    needs:
      - job_001
      - job_002
